// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggj-C5u_NeLRVi5Myym1xFcYppgmsAwY',
    appId: '1:527756338262:web:adc5928eaa1a989ceec7f7',
    messagingSenderId: '527756338262',
    projectId: 'chatapplication-b4644',
    authDomain: 'chatapplication-b4644.firebaseapp.com',
    storageBucket: 'chatapplication-b4644.appspot.com',
    measurementId: 'G-R7JGJ8G54R',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyB5UEhi83bV11yDfgFX7WACEbXKaafxgh0",
      appId: "1:881383890993:android:d0c0a0b1ca0350967cf510",
      messagingSenderId: "881383890993",
      projectId: "prepilly-31aeb",
      storageBucket: "prepilly-31aeb.appspot.com");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNx2VTmhZLj9uppXoO4JdhLv7GrSEx7Bk',
    appId: '1:881383890993:ios:dd24f674dfe1e4407cf510',
    messagingSenderId: '647295400944',
    projectId: 'prepilly-31aeb',
    storageBucket: 'prepilly-31aeb.appspot.com',
    iosBundleId: 'com.example.tPotal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZMsYuQMg45-njvLToG5Gx031RlaDLjdU',
    appId: '1:527756338262:ios:aaf9fa691c18b736eec7f7',
    messagingSenderId: '527756338262',
    projectId: 'chatapplication-b4644',
    storageBucket: 'chatapplication-b4644.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggj-C5u_NeLRVi5Myym1xFcYppgmsAwY',
    appId: '1:527756338262:web:ea8084ba6d6bcd16eec7f7',
    messagingSenderId: '527756338262',
    projectId: 'chatapplication-b4644',
    authDomain: 'chatapplication-b4644.firebaseapp.com',
    storageBucket: 'chatapplication-b4644.appspot.com',
    measurementId: 'G-16TR8KCZNP',
  );
}
